ALTER TABLE entries ADD COLUMN IF NOT EXISTS quiz_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS correct_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS force_include_in_quiz BOOLEAN NOT NULL DEFAULT FALSE;
